### PR TITLE
Fix #292

### LINKED ISSUE #292: One Click Heroku Deploy
Augur Node should be deployable with Heroku's one-click deploy.

Please join the #dev or #bounties channel of our [Discord](http://augur.net/invite) with any questions. 

Bounty posted with [Gitcoin](https://gitcoin.co).

### PR DESCRIPTION
**Pull request by JonnyBurger**

### CODE REVIEW

**Comment by vs77bb** [comment]
@JonnyBurger Poking in to make sure you saw the feedback on this PR!

**Comment by pgebheim** [comment]
Hi!

Yes, I mean removing the Deploy button in the readme until we we can run our unit test suite against Heroku as well as Sqlite.

**Comment by tinybike** [comment]
@pgebheim what's the status of this?  We can't just leave these bounties in limbo.  If this is inadequate, it should be closed; otherwise merge it and let's pay out the bounty.

**Comment by JonnyBurger** [comment]
Postgres seems to work, I will return soon ans clean it up and ask you to review it.

**Comment by gkaemmer** [comment]
PostgreSQL compatibility seems like an important piece here--is it likely this will be rebased and merged soon?

**Comment by JonnyBurger** [comment]
Hi guys,

added another commit so there is no merge conflict with the newest master.

You can also reach out to me e.g. on Twitter where we can chat in realtime to resolve the last few issues.

**Comment by pgebheim** [comment]
Closing -- this PR is being merged into a new PR #620

**Comment by pgebheim** [comment]
Hey @JonnyBurger  -- merged in the cleaned up version of this patch in #620!!!

Thanks for that great base to start with.

**Comment by JonnyBurger** [comment]
Yes!! Awesome, congrats!
Happy that it got merged.
Thanks for doing the final refactoring yourself and thanks for the collaboration opportunity!

**Comment by vs77bb** [comment]
@JonnyBurger Any chance you're on [Gitcoin Slack](gitcoin.co/slack)? Would love to DM you about a few bounties to come -- great work here!

**Comment by JonnyBurger** [comment]
@vs77bb
Awesome, can you email me?

hi@jonny.io

**Pull request closed without merging**
