### PR TITLE
Github: Parity Node: Could not find balance for token decrease

### PR DESCRIPTION
**Pull request by epheph**
Story details: https://app.clubhouse.io/augur/story/15116

### CODE REVIEW

**Comment by epheph** [comment]
"If no logs were included in this batch, grab the first, middle, and last block number and fetch those details. If we don't receive any block details, but also don't receive an error, inform the user they likely have a partially-sync'd warp node

**Comment by justinbarry** [comment]
@epheph I'm getting an error when building:
`Error:(1, 17) TS2305: Module '"augur-node/node_modules/augur.js/index"' has no exported member 'BlockRange'.`

**Comment by pgebheim** [comment]
Ok we'll need to add that type import I think

**Comment by justinbarry** [comment]
This will never pass w/o an augur.js release.

**Comment by justinbarry** [comment]
Was merged in as part of #660

**Pull request closed without merging**
