### PR TITLE
Add double quotes to CREATE TABLE statement

### PR DESCRIPTION
**Pull request by adrake33**
GH issue: https://github.com/AugurProject/augur-node/issues/714

### CODE REVIEW

**Comment by epheph** [comment]
This is an improvement, but even better is using the native knex schema functional format
👍

**Comment by adrake33** [comment]
@epheph Ah, ok. So would the `return knex.schema.raw` line look like this instead:

```
return knex.schema.createTable("transactionHashes", (table: Knex.CreateTableBuilder): void => {
      table.string("transactionHash", 66).primary().notNullable();
      table.integer("blockNumber").notNullable();
      table.boolean("orphaned").defaultTo(0);
    });
```

**Comment by epheph** [comment]
Yas. Looks really nice.

And i think we've run into that whole boolean/0 thing before and thought the way you did it there is correct?

**Comment by adrake33** [comment]
I think so? It's done that way in the orders.ts file.

**Comment by epheph** [comment]
👍 ship it!

**Pull request merged**
