### PR TITLE
match deployment blocks from augur-contracts PR

### PR DESCRIPTION
**Pull request by epheph**
https://github.com/AugurProject/augur-contracts/pull/4

### CODE REVIEW

**Comment by epheph** [comment]
@tinybike familiar with this CI failure?

**Comment by MicahZoltu** [comment]
@epheph Your CI script needs to run `tsc` in the root of the project before running the tests.

**Comment by epheph** [comment]
Oh, it looks like build was committed previously, that's why this just popped up.

@pgebheim

**Comment by tinybike** [comment]
Shouldn't we retain the old upload block numbers, if we're also picking up LegacyRepContract events?

**Comment by epheph** [comment]
yea, makes sense

**Pull request closed without merging**
