### PR TITLE
Return timestamp in result from get-markets-created-by-user

### PR DESCRIPTION
**Pull request by kennsippell**
https://app.clubhouse.io/augur/story/4855/return-timestamp-in-result-from-get-markets-created-by-user-and-get-reporting-history

### CODE REVIEW

**Comment by kennsippell** [comment]
Note this work item also calls for creationTime in get-reporting-history, but this appears to already be in place.

**Comment by epheph** [comment]
Looks great.

@bthaile @stephensprinkle this changes the format of the response, from an array to an object, so we can include timestamp. this was implemented as 
```
[{ marketID, timestamp}]
```

but would probably be just as easy to write as
```{ marketID: timestamp }```

if that's what the UI needs?

thx @kennsippell

**Comment by kennsippell** [comment]
it's actually ```[{ marketID, creationTime }]```

**Comment by epheph** [comment]
discussion in #ui, we should use our existing strategy, "you get marketIDs from various APIs, then feed them into getMarketsInfo to resolve more details" and not bother marketID-returning APIs with returning specific data

**Pull request closed without merging**
